services:
  backend:
    build:
      context: ./backend          
      dockerfile: Dockerfile          
    ports:
      - "8080:8080"
    environment:
      - UNSPLASH_API_KEY
    command: ["java", "-jar", "app.jar"]

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    depends_on:
      - backend
